#!/usr/bin/env sh

yabai -m config layout                      float
yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off
yabai -m config window_placement            second_child
yabai -m config window_topmost              off
yabai -m config window_shadow               on
yabai -m config window_opacity              off
yabai -m config split_ratio                 0.50
yabai -m config auto_balance                off

yabai -m signal --add event=space_changed   \
  action="sketchybar --trigger space_change"
yabai -m signal --add event=display_changed \
  action="sketchybar --trigger space_change"

yabai -m signal --add event=space_created   \
  action="sketchybar --trigger space_set_change"
yabai -m signal --add event=space_destroyed \
  action="sketchybar --trigger space_set_change"

# Escape the variable so yabai expands it when the event fires.
yabai -m signal --add label=spacetag_window_destroyed event=window_destroyed \
  action="sketchybar --trigger window_destroyed WIN=\$YABAI_WINDOW_ID"

echo "yabai config loaded ($(date '+%H:%M:%S'))."
