#!/bin/sh

log() { echo "$*" >> "${STUB_LOG:?}"; }

if [ "${1:-}" = -m ] && [ "${2:-}" = query ]; then
  log "yabai query ${3:-} ${4:-}"
  case "${3:-}" in
    --spaces)
      [ "${STUB_NO_SPACE:-0}" = 1 ] && exit 1
      printf '{"index":%s}\n' "${STUB_SPACE_INDEX:-1}"
      ;;
    --displays)
      [ "${STUB_NO_DISPLAY:-0}" = 1 ] && exit 1
      printf '{"uuid":"%s"}\n' "${STUB_DISPLAY_UUID:-TEST-UUID-1}"
      ;;
  esac
  exit 0
fi

if [ "${1:-}" = -m ] && [ "${2:-}" = space ]; then
  log "yabai label sid=${3:-} value=[${5:-}]"
  [ "${STUB_LABEL_FAIL:-0}" = 1 ] && exit 1
  exit 0
fi

log "yabai other: $*"
exit 0
